### ISSUE TITLE
Command execution error

### ISSUE THREAD

**Issue by meshchaninov** [jk1/youtrack-idea-plugin#142]
When I try to make any command to youtrack. This error appears

`
Command execution error: class com.google.gson.JsonObject cannot be cast to class com.google.gson.JsonArray (com.google.gson.JsonObject and com.google.gson.JsonArray are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @66480dd7)
`

But I can view any data from the server

**Comment by jk1** [comment]
Hi Nikita,

Would you mind specifying the plugin version you use? 
Attaching the IDE log will help a lot as well.

**Comment by meshchaninov** [comment]
IDE: Pycharm 2020.2
OS: Mac OS 10.15.6
Youtrack-idea-plugin v: 1.0.4

**Comment by meshchaninov** [comment]
> Attaching the IDE log will help a lot as well.

Event log?
In event log only that exception is printed

**Comment by jk1** [comment]
What I've meant is the IDE log file. 
Here's how to locate it: https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by meshchaninov** [comment]
2020-10-10 03:17:51,976 [ 625430]  ERROR -        com.github.jk1.ytplugin - PyCharm 2020.2.2  Build #PC-202.7319.64 
2020-10-10 03:17:51,976 [ 625430]  ERROR -        com.github.jk1.ytplugin - JDK: 11.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-10-10 03:17:51,976 [ 625430]  ERROR -        com.github.jk1.ytplugin - OS: Mac OS X 
2020-10-10 03:17:51,977 [ 625431]  ERROR -        com.github.jk1.ytplugin - Plugin to blame: YouTrack Integration version: 1.0.4 
2020-10-10 03:18:09,245 [ 642699]   INFO -        com.github.jk1.ytplugin - Failed to load eligible visibility groups for issue 
2020-10-10 03:18:09,248 [ 642702]   INFO - .idea.vim.command.CommandState - Push new mode state: COMMAND:NONE 
2020-10-10 03:18:09,249 [ 642703]   INFO - .idea.vim.command.CommandState - Push new mode state: INSERT:NONE 
2020-10-10 03:18:09,249 [ 642703]   INFO - ome.idea.vim.group.ChangeGroup - Reset caret to a non-block shape 
2020-10-10 03:18:14,808 [ 648262]  ERROR -        com.github.jk1.ytplugin - Command execution error 
java.lang.ClassCastException: class com.google.gson.JsonObject cannot be cast to class com.google.gson.JsonArray (com.google.gson.JsonObject and com.google.gson.JsonArray are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @66480dd7)
	at com.github.jk1.ytplugin.rest.CommandRestClient.getGroupId(CommandRestClient.kt:47)
	at com.github.jk1.ytplugin.rest.CommandRestClient.executeCommand(CommandRestClient.kt:60)
	at com.github.jk1.ytplugin.commands.CommandService$executeAsync$1.run(CommandService.kt:36)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jk1** [comment]
Thanks, it helps a lot.
We'll look deeper into the issue and post back shortly.

**Comment by lesslyrics** [comment]
Resolved, should be released in bugfix 1.0.5

**Comment by meshchaninov** [comment]
Cool! Thanks😁

вт, 13 окт. 2020 г., 21:05 Alina <notifications@github.com>:

**Comment by meshchaninov** [comment]
When the next release?

**Comment by jk1** [comment]
@meshchaninov one can expect it in a week of so. 
We still have something to add there.

**Comment by meshchaninov** [comment]
It's works!
